language: python
branches:
  only:
  - develop
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
- make publish github
env:
  global:
    secure: YmCl0tsDagkvvtB4jJMkRm8AeA+FD3dUEbVGZlWYI66fIbxz5snD2vA4bgBY6PtLJE6alZDEe05J7j6Kc8jv9KvdPbZdB6VmuZ5cmz6YkZDH40NX/cUC5TcQYoGGQqTrC/Q3lJ4uyCZttt8UBe/tV1Z3AdaMLQU647WJnCYA0NRdlWc+VRYfnBDtfIOxtvi/lF9xmkLfOfCi0h5zAXRKLGQwk5dvPelHBRCSXRG73yFFfRRLklC1J9Z511SdtBGB/hqfQQoieiw2nt8m462kHUA/DmC6C4//CTqcYTxBwpYTe1J2D+XnqoJp18fcPVHhqaiS+FcvSenyS0bxEdn4uewenn9DwfUr2lKuzOvYUQJpt9WR5Nn8ORZAPjeWOGv0OTmQvKHlkelYgo0RWArin179OOshepq9mSNkSbnPjwP046KpFERz2Idq4HZ0oJHXlZ/6RdMtQmA45D0bP1jmNUEA6+LxYd1IKiP1kx88tG/Uf1BvIUTeA+2dzvovsfwfbpMZXIj8u0Hv++x/wtWECyenEs1ox5TFgU7b/qWkhNZylABAHDT1mPGfDghmGQ+80tX8khtk6X56VbksUHAaDuI3GHWSVEsobQb833p178X9pmTTKuKYSHdboiQ5zvrKk6gOaJX0TIfgN8GTt+IAF9hEIWZ+hkjhxI1hpEkfchE=
